StartupEvents.registry('block', event => {
	
	// Mortared Stone - Basic Tier
	event.create('runefall:mortared_stone')
		.displayName('Mortared Stone')
		.soundType('stone')
		.hardness(2.0)
		.resistance(6.0)
		.tagBoth('runefall:tiered_stones')
		.tagBoth('runefall:tiered_stones/tiers/basic')
		.requiresTool(true)
		.tagBlock('minecraft:needs_stone_tool')
		.tagBlock('minecraft:mineable/pickaxe')
		.textureAll('runefall:block/tiered_stones/mortared_stone')
	
	// Hardened Stone - Refined Tier
	event.create('runefall:hardened_stone')
		.displayName('Mortared Stone')
		.soundType('stone')
		.hardness(2.5)
		.resistance(6.0)
		.tagBoth('runefall:tiered_stones')
		.tagBoth('runefall:tiered_stones/tiers/refined')
		.requiresTool(true)
		.tagBlock('minecraft:needs_stone_tool')
		.tagBlock('minecraft:mineable/pickaxe')
		.textureAll('runefall:block/tiered_stones/hardened_stone')
		
	// Ashlar Stone - Advanced Tier
	event.create('runefall:ashlar_stone')
		.displayName('Ashlar Stone')
		.soundType('stone')
		.hardness(3.5)
		.resistance(8.0)
		.tagBoth('runefall:tiered_stones')
		.tagBoth('runefall:tiered_stones/tiers/advanced')
		.requiresTool(true)
		.tagBlock('minecraft:needs_stone_tool')
		.tagBlock('minecraft:mineable/pickaxe')
		.textureAll('runefall:block/tiered_stones/ashlar_stone')
	
	// Enchanted Stone - Exquisite Tier
	event.create('runefall:enchanted_stone')
		.displayName('Enchanted Stone')
		.soundType('stone')
		.hardness(4.5)
		.resistance(12.0)
		.tagBoth('runefall:tiered_stones')
		.tagBoth('runefall:tiered_stones/tiers/exquisite')
		.requiresTool(true)
		.tagBlock('minecraft:needs_iron_tool')
		.tagBlock('minecraft:mineable/pickaxe')
		.textureAll('runefall:block/tiered_stones/enchanted_stone')

	// Enchanted Hardened Stone - Exquisite Tier
	event.create('runefall:enchanted_hardened_stone')
		.displayName('Enchanted Hardened Stone')
		.soundType('stone')
		.hardness(6.0)
		.resistance(16.0)
		.tagBoth('runefall:tiered_stones')
		.tagBoth('runefall:tiered_stones/tiers/exquisite')
		.requiresTool(true)
		.tagBlock('minecraft:needs_iron_tool')
		.tagBlock('minecraft:mineable/pickaxe')
		.textureAll('runefall:block/tiered_stones/enchanted_hardened_stone')
		
	// Enchanted Mortared Stone - Flawless Tier
	event.create('runefall:enchanted_mortared_stone')
		.displayName('Enchanted Mortared Stone')
		.soundType('stone')
		.hardness(8.0)
		.resistance(24.0)
		.tagBoth('runefall:tiered_stones')
		.tagBoth('runefall:tiered_stones/tiers/flawless')
		.requiresTool(true)
		.tagBlock('minecraft:needs_diamond_tool')
		.tagBlock('minecraft:mineable/pickaxe')
		.textureAll('runefall:block/tiered_stones/enchanted_mortared_stone')
		
	// Ashlar Manastone - Flawless Tier
	event.create('runefall:ashlar_manastone')
		.displayName('Ashlar Manastone')
		.soundType('stone')
		.hardness(12.0)
		.resistance(32.0)
		.tagBoth('runefall:tiered_stones')
		.tagBoth('runefall:tiered_stones/tiers/flawless')
		.requiresTool(true)
		.tagBlock('minecraft:needs_diamond_tool')
		.tagBlock('minecraft:mineable/pickaxe')
		.textureAll('runefall:block/tiered_stones/ashlar_manastone')
	
	
	console.log('Registered Tiered Stone Blocks')
})